apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rengha-tech-docs
  description: rengha-tech-docs-description
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
